name: Ruff Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: astral-sh/ruff-action@v3
    - name: Ruff Linting
    - run: ruff check --fix
    - run: ruff format
