name: Ruff Linting

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Ruff Linting
      uses: astral-sh/ruff-action@v3
    - run: ruff check
